name: 'Evaluate OPAL Gates'
description: 'Evaluates security and quality gates using OPA/OPAL policy engine'

inputs:
  snyk-results-path:
    description: 'Path to Snyk results JSON'
    required: false
    default: 'snyk-results.json'
  quality-results-path:
    description: 'Path to quality gate results JSON'
    required: false
    default: 'quality-gate-result.json'
  jira-exceptions-path:
    description: 'Path to Jira exceptions JSON'
    required: false
    default: ''
  opa-url:
    description: 'OPA REST API URL'
    required: false
    default: 'http://localhost:8181'
  user-key:
    description: 'GitHub actor username'
    required: true
  repository:
    description: 'Repository name (org/repo)'
    required: false
    default: ''
  debug-mode:
    description: 'Enable debug mode'
    required: false
    default: 'false'

outputs:
  gate-result:
    description: 'Combined gate result (0=pass, 1=warning, 2=blocked)'
    value: ${{ steps.evaluate.outputs.gate-result }}
  gate-decision:
    description: 'Gate decision string (PASS/WARNING/BLOCKED/PASS_WITH_EXCEPTION)'
    value: ${{ steps.evaluate.outputs.gate-decision }}
  security-result:
    description: 'Security gate result'
    value: ${{ steps.evaluate.outputs.security-result }}
  quality-result:
    description: 'Quality gate result'
    value: ${{ steps.evaluate.outputs.quality-result }}
  has-exception:
    description: 'Whether Jira exception was applied'
    value: ${{ steps.evaluate.outputs.has-exception }}
  exception-ticket:
    description: 'Jira ticket ID if exception applied'
    value: ${{ steps.evaluate.outputs.exception-ticket }}

runs:
  using: 'composite'
  steps:
    - name: Prepare evaluation environment
      shell: bash
      run: |
        echo "Preparing OPAL gate evaluation..."
        echo "  User: ${{ inputs.user-key }}"
        echo "  OPA URL: ${{ inputs.opa-url }}"
        echo "  Snyk Results: ${{ inputs.snyk-results-path }}"
        echo "  Quality Results: ${{ inputs.quality-results-path }}"

        # Ensure scripts are executable
        if [ -f ".github/scripts/evaluate-gates.sh" ]; then
          chmod +x .github/scripts/evaluate-gates.sh
        fi

    - name: Validate inputs
      shell: bash
      run: |
        # Check Snyk results
        if [ -f "${{ inputs.snyk-results-path }}" ]; then
          echo "Snyk results found: ${{ inputs.snyk-results-path }}"
        else
          echo "Warning: Snyk results not found, creating empty file"
          echo '{"vulnerabilities":[],"ok":true}' > "${{ inputs.snyk-results-path }}"
        fi

        # Check quality results
        if [ -f "${{ inputs.quality-results-path }}" ]; then
          echo "Quality results found: ${{ inputs.quality-results-path }}"
        else
          echo "Warning: Quality results not found, creating empty file"
          echo '{"projectStatus":{"status":"UNKNOWN"}}' > "${{ inputs.quality-results-path }}"
        fi

        # Check Jira exceptions
        if [ -n "${{ inputs.jira-exceptions-path }}" ] && [ -f "${{ inputs.jira-exceptions-path }}" ]; then
          EXCEPTION_COUNT=$(jq '.exceptions | length // 0' "${{ inputs.jira-exceptions-path }}" 2>/dev/null || echo 0)
          echo "Jira exceptions found: $EXCEPTION_COUNT"
        else
          echo "No Jira exceptions file provided"
        fi

    - name: Evaluate OPAL Gates
      id: evaluate
      shell: bash
      env:
        OPA_URL: ${{ inputs.opa-url }}
        USER_KEY: ${{ inputs.user-key }}
        DEBUG: ${{ inputs.debug-mode }}
      run: |
        echo "Evaluating OPAL security gates..."

        # Build arguments for evaluate-gates.sh
        ARGS="${{ inputs.snyk-results-path }} ${{ inputs.quality-results-path }}"

        if [ -n "${{ inputs.jira-exceptions-path }}" ] && [ -f "${{ inputs.jira-exceptions-path }}" ]; then
          ARGS="$ARGS ${{ inputs.jira-exceptions-path }}"
        fi

        # Run evaluation script
        set +e
        if [ -f ".github/scripts/evaluate-gates.sh" ]; then
          ./.github/scripts/evaluate-gates.sh $ARGS
          GATE_RESULT=$?
        else
          echo "Error: evaluate-gates.sh not found"
          GATE_RESULT=2
        fi
        set -e

        echo "Gate evaluation exit code: $GATE_RESULT"
        echo "gate-result=$GATE_RESULT" >> $GITHUB_OUTPUT

        # Determine decision based on exit code
        case $GATE_RESULT in
          0)
            DECISION="PASS"
            ;;
          1)
            DECISION="WARNING"
            ;;
          2)
            DECISION="BLOCKED"
            ;;
          *)
            DECISION="UNKNOWN"
            ;;
        esac

        # Check for OPA response details if available
        HAS_EXCEPTION="false"
        EXCEPTION_TICKET=""
        SECURITY_RESULT=$GATE_RESULT
        QUALITY_RESULT=0

        if [ -f /tmp/opa-response.json ]; then
          DECISION=$(jq -r '.result.decision // "'"$DECISION"'"' /tmp/opa-response.json 2>/dev/null || echo "$DECISION")
          SECURITY_RESULT=$(jq -r '.result.gates.security.exit_code // '"$GATE_RESULT"'' /tmp/opa-response.json 2>/dev/null || echo "$GATE_RESULT")
          QUALITY_RESULT=$(jq -r '.result.gates.quality.exit_code // 0' /tmp/opa-response.json 2>/dev/null || echo "0")
          HAS_EXCEPTION=$(jq -r '.result.exception.has_exception // false' /tmp/opa-response.json 2>/dev/null || echo "false")
          EXCEPTION_TICKET=$(jq -r '.result.exception.ticket // ""' /tmp/opa-response.json 2>/dev/null || echo "")

          if [ "$HAS_EXCEPTION" = "true" ]; then
            DECISION="PASS_WITH_EXCEPTION"
          fi
        fi

        echo "gate-decision=$DECISION" >> $GITHUB_OUTPUT
        echo "security-result=$SECURITY_RESULT" >> $GITHUB_OUTPUT
        echo "quality-result=$QUALITY_RESULT" >> $GITHUB_OUTPUT
        echo "has-exception=$HAS_EXCEPTION" >> $GITHUB_OUTPUT
        echo "exception-ticket=$EXCEPTION_TICKET" >> $GITHUB_OUTPUT

        echo ""
        echo "========================================"
        echo "  GATE EVALUATION COMPLETE"
        echo "========================================"
        echo "  Decision: $DECISION"
        echo "  Exit Code: $GATE_RESULT"
        echo "  Security Gate: $SECURITY_RESULT"
        echo "  Quality Gate: $QUALITY_RESULT"
        echo "  Exception Applied: $HAS_EXCEPTION"
        if [ -n "$EXCEPTION_TICKET" ]; then
          echo "  Exception Ticket: $EXCEPTION_TICKET"
        fi
        echo "========================================"

    - name: Generate gate evaluation summary
      shell: bash
      run: |
        GATE_RESULT="${{ steps.evaluate.outputs.gate-result }}"
        DECISION="${{ steps.evaluate.outputs.gate-decision }}"
        SECURITY="${{ steps.evaluate.outputs.security-result }}"
        QUALITY="${{ steps.evaluate.outputs.quality-result }}"
        HAS_EXC="${{ steps.evaluate.outputs.has-exception }}"
        EXC_TICKET="${{ steps.evaluate.outputs.exception-ticket }}"

        # Determine status icon
        case $GATE_RESULT in
          0) STATUS_ICON="PASS" ;;
          1) STATUS_ICON="WARNING" ;;
          2) STATUS_ICON="BLOCKED" ;;
          *) STATUS_ICON="UNKNOWN" ;;
        esac

        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## OPAL Gate Evaluation Results

        | Parameter | Value |
        |-----------|-------|
        | **Decision** | **$DECISION** |
        | Exit Code | $GATE_RESULT |
        | User | ${{ inputs.user-key }} |
        | Repository | ${{ inputs.repository }} |

        ### Gate Details

        | Gate | Exit Code | Status |
        |------|-----------|--------|
        | Security Gate | $SECURITY | ${SECURITY:-0} |
        | Quality Gate | $QUALITY | ${QUALITY:-0} |

        EOF

        if [ "$HAS_EXC" = "true" ]; then
          cat >> $GITHUB_STEP_SUMMARY << EOF

        ### Jira Exception Applied

        | Field | Value |
        |-------|-------|
        | Ticket | $EXC_TICKET |
        | Status | Exception approved and applied |

        EOF
        fi

        # Add enforcement message
        case $GATE_RESULT in
          0)
            echo "**Deployment Authorized**" >> $GITHUB_STEP_SUMMARY
            ;;
          1)
            echo "**Warning:** Non-blocking issues detected. Deployment continues but issues should be addressed." >> $GITHUB_STEP_SUMMARY
            ;;
          2)
            echo "**Deployment Blocked:** Create a Jira exception ticket to bypass this gate." >> $GITHUB_STEP_SUMMARY
            ;;
        esac
